name: iThelp Login

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: Login to iThelp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Login to iThelp
        run: python main.py
        env:
          ITHELP_ACCOUNT: ${{ secrets.ITHELP_ACCOUNT }}
          ITHELP_PASSWORD: ${{ secrets.ITHELP_PASSWORD }}
